apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  name: gluster
subsets:
- addresses:
  - ip: 192.168.0.110
  - ip: 192.168.0.171
  - ip: 192.168.0.5
  ports:
  - port: 1
    protocol: TCP
